name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite
  workflow_dispatch:     # permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: gabrielcaixeta01
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
