name: Generate Snake

on:
  schedule:
    # Executa todo dia às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: gabrielcaixeta01
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
